---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: dev
  url: https://github.com/vfiftyfive/CFD12-Demo-Manifests.git

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: dev
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./overlay/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: dev
  targetNamespace: dev

